### ISSUE TITLE
[Bug] TWRP Mount root at SYSTEM_ROOT

### ISSUE THREAD

**Issue by MartinX3** [MartinX3-AndroidDevelopment/bug_tracker#2]
**Platform:** TAMA
**Device:** AKARI, APOLLO, AURORA, AKATSUKI
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
The root should get mounted at /SYSTEM_ROOT
The system should get mounted at /SYSTEM

**Symptoms**
The root gets mounted at /SYSTEM
The system gets mounted at /SYSTEM/SYSTEM
This leads to symlink loops if at root a symlink wants to redirect to system, but instead now redirect to itself

**How to reproduce**
Boot into TWRP

**Comment by MartinX3** [comment]
https://github.com/omnirom/android_bootable_recovery/blob/android-9.0/etc/init.rc
contains the line
`export ANDROID_ROOT /system`
should it be renamed it
`export ANDROID_ROOT /system_root`
?

Edit: Nope, doesn't fix the misbehaviour

Edit0:
But it should, according to
https://gerrit.omnirom.org/#/c/android_bootable_recovery/+/32033/
https://gerrit.omnirom.org/#/c/android_bootable_recovery/+/32034/
https://github.com/omnirom/android_bootable_recovery/blob/5ab596451a0d4eb56f96083fc3e3c204401132e0/etc/init.rc#L29
https://github.com/omnirom/android_bootable_recovery/blob/f5955b1cb44c0ced5983207c55f0013a4586b284/partitionmanager.cpp#L2828

**Comment by MartinX3** [comment]
Change Mount in twrp.fstab to
/system_root    ext4    /dev/block/bootdevice/by-name/system			flags=slotselect;display="System";wipeingui
?

Thank you @gouster4 for the idea

Edit:
the tama problem is fixed or workarounded by setting in fstab
`/system_root         ext4    /dev/block/bootdevice/by-name/system            flags=slotselect`
then `/system_root` is the correct root
`/system` is the system
`/system_root/system` is the correct symlink

**Comment by Gouster4** [comment]
> Change Mount in twrp.fatab to
> /system_root ext4 /dev/block/bootdevice/by-name/system	flags=slotselect;display="System";wipeingui
> ?
> 
> Thank you @Gouster4 for the idea

Yes, should be all, as TWRP already contains sysmlink /system to /system_root/system

wipeingui is needed because twrp wipe search for /system target partition which doesnt exist, this makes new entry, old entry dissapeared as partitions mounted to /system wasnt found.

display="System" needed to show correct name in mount gui. original name was system_root

slotselect was used also on old system mountpoint. tells twrp that we have system_a and system_b partitions.

**Comment by Gouster4** [comment]
> https://github.com/omnirom/android_bootable_recovery/blob/android-9.0/etc/init.rc
> contains the line
> `export ANDROID_ROOT /system`
> should it be renamed it
> `export ANDROID_ROOT /system_root`
> ?

this is maybe better way to fix wipegui entry and mountgui name i did in fstab. try it.

**Comment by MartinX3** [comment]
10.0 enforces SAR for every device.
The upcoming TWRP for 10.0 will fix this issue.
