### ISSUE TITLE
[Bug] Light/Dark mode switcher bug on Sony AOSP rom XZ3

### ISSUE THREAD

**Issue by ozamyatin** [MartinX3-AndroidDevelopment/bug_tracker#20]
Platform: Tama
Device: Akatsuki (XZ3 Dual Sim) 9436
Kernel version: 4.9.x
Android version: 9.0.x

Description
When trying to change theme from default light to dark in Sony AOSP Rom settings nothing happens. Theme does not change.

Please note that neither theme changer, nor invert color setting do work.

Symptoms
No reaction, as if no setting was changed.

How to reproduce
Open settings app, choose display. Scroll down and choose theme settings. Choose dark.

**Comment by MartinX3** [comment]
https://github.com/sonyxperiadev/bug_tracker/issues/415

Aaaand delegated :)

The full black theme comes with android Q.
Android P has only minimal changes in this direction.

But OmniROM may satisfy your needs better with the themes in the OmniROM settings app. :)
