### ISSUE TITLE
[BUG] Blank screen after bootloader with AOSP 12.0/12.1

### ISSUE THREAD

**Issue by mvanboven** [MartinX3-AndroidDevelopment/bug_tracker#51]
Platform: TAMA
Device: XZ3 (AKATSUKI)
Kernel version: 4.19
Android version: 12.0/12.1

*Previously working on**
Has this always been a problem, or is it a new issue? New issue, had no problems in the past with Android 11

[logcat.txt](https://github.com/sonyxperiadev/bug_tracker/files/8778294/logcat.txt)

**Comment by MartinX3** [comment]
Closed in favor of upstream issue ticket https://github.com/sonyxperiadev/bug_tracker/issues/775
