### ISSUE TITLE
[Bug] Black camera Preview - 10.0 works without the fix

### ISSUE THREAD

**Issue by ZioFrengo** [MartinX3-AndroidDevelopment/bug_tracker#7]
**Platform:** TAMA
**Device:** APOLLO
**Kernel version:** 4.9
**Android version:** 9.0

**Description**
Even if I mount the fix for the camera, I still have the problem of the black preview, why? 

**Symptoms**
Black Preview

**How to reproduce**
After flash the camera fix

**Comment by MartinX3** [comment]
If you unlocked your phone on PIE, please don't install the camerafix.zip
But if the preview is black without the camerafix (if installed by accident reflash the vendor.sin/vendor.img/vendorpartition), follow the following instructions.

If you unlocked it on OREO,
- [ ] Downgrade to OREO (needs fullwipe to boot the device)
- [ ] Execute XPERIFIX on OREO (custom installation, VENDOR, A/B, magisk.zip) & permissive.zip (only in oreo)
- [ ] Take a picture on OREO (if the camera preview works, all is correct) -> only do it once on a device
- [ ] Upgrade to PIE
- [ ] fastboot --disable-verity --disable-verification flash vbmeta vbmeta.img -> if any error happen, you use the wrong fastboot version
- [ ] Install camerafix.zip in TWRP

If this problem still occur, I can reopen this issue.
Have fun. :)

PS:
If you use 10.0 you don't need any fix at all.
It is still recommend to unlock the bootloader only on the newest possible stock rom, but Oreo and Pie unlockers should be equally happy now without any camera issues.

**Comment by ZioFrengo** [comment]
Thank you!!!

**Comment by ZioFrengo** [comment]
I did all the steps, but the problem is not solved even in oreo.  XperiFix does not go and the file permissive.zip I don't know where it is

**Comment by MartinX3** [comment]
In the actual twrp bundles is this file.
You need as magisk addon, or the xperifix doesn't work in Oreo.

**Comment by ZioFrengo** [comment]
If it is not a problem, you could explain to me step by step the whole procedure in detail because I am going crazy ahahahahaha

**Comment by MartinX3** [comment]
Here :P
https://github.com/MartinX3sAndroidDevelopment/bug_tracker/issues/7#issuecomment-481327471

**Comment by ZioFrengo** [comment]
I find permissive.zip  in the twrp pie directory right?

**Comment by MartinX3** [comment]
Yes :)

**Comment by ZioFrengo** [comment]
is version 51.1.a.11.51 right for XperiFix?

**Comment by MartinX3** [comment]
My uploaded Oreo firmware? Yes.

**Comment by ZioFrengo** [comment]
should I flash permissive before or after xperifix??

**Comment by MartinX3** [comment]
Both is fine, just follow the instructions :)

**Comment by ZioFrengo** [comment]
even if I follow all the steps the fix doesn't work

**Comment by MartinX3** [comment]
Selinux is permissive and the xperifix files are in place?
Drmfix.so and drmfuck.so are in vendor? 

You did a restart at the end?

**Comment by ZioFrengo** [comment]
Yes it's all where it should be, by chance should magisk be version 18.1?  Or is the version in the folder ok anyway?

**Comment by MartinX3** [comment]
Magisk must be 18.1 on stock (until the bootloop got fixed) and on sodp based roms your boot 18.1 once and upgrade to 19.3 or newer.

**Comment by aka-charos** [comment]
Some general instructions to help others for the Oreo steps:
	
- Flash with newflasher OREO H8324_Customized+CE1_1313-3194_51.1.A.11.51_R8A (found at https://androidfilehost.com/?w=files&flid=288272)
- fastboot reboot bootloader

- fastboot flash boot C:\Users\R3drum\Downloads\2018-10-11_16.20+2.00_51.1.A.11.51.tar\twrp-3.2.3-0-xz2c.img

- fastboot --disable-verity --disable-verification flash vbmeta C:\Users\R3drum\Downloads\2018-10-11_16.20+2.00_51.1.A.11.51.tar\vbmeta-xz2c.img

- fastboot reboot > enter TWRP > Advanced >Adb Sideload

- adb sideload C:\Users\R3drum\Downloads\2018-10-11_16.20+2.00_51.1.A.11.51.tar\stockkernel-xz2c-installer.zip

- adb sideload C:\Users\R3drum\Downloads\2018-10-11_16.20+2.00_51.1.A.11.51.tar\twrp-3.2.3-0-xz2-xz2c-xz2p-installer.zip

- adb sideload C:\Users\R3drum\Downloads\2018-10-11_16.20+2.00_51.1.A.11.51.tar\Magisk-v17.1.zip

- Reboot to ROM and then shutdown again

- Enter into TWRP and enable adb : adb sideload C:\Users\R3drum\Downloads\2019-11-16_10-27-04_twrp_stock_xz2c_52.0.A.11.32.tar\permissive.zip

- Run XperiFIX > Flash Magisk and  VENDOR and  A/B

- Boot to ROM, camera works on Oreo

**Comment by aka-charos** [comment]
- Flash 1311-5320 51.1.a.11.51 with Emma > Camera does not work

- Enter fastboot > adb reboot bootloader

- fastboot --disable-verity --disable-verification flash vbmeta C:\Users\R3drum\Downloads\2019-11-16_10-27-04_twrp_stock_xz2c_52.0.A.11.32.tar\vbmeta.img 

- fastboot boot C:\Users\R3drum\Downloads\2019-11-16_10-27-04_twrp_stock_xz2c_52.0.A.11.32.tar\twrp-xz2c.img

- adb sideload C:\Users\R3drum\Downloads\2019-11-16_10-27-04_twrp_stock_xz2c_52.0.A.11.32.tar\[Pie]Camera_fix_by_MartinX3.zip

Reboot to Rom > **Camera works**!

**Comment by MartinX3** [comment]
@aka-charos 
Thank you :)
Or upgrade to 10.0.
I heard there the camera now works for Oreo and Pie unlocker equally without any fix.

**Comment by aka-charos** [comment]
That's good news Martin. Do you happen to know if on Android 10 for Oreo unlockers it "just works" (poor camera quality) or properly works (no quality degradation in camera) ?

**Comment by MartinX3** [comment]
@aka-charos 
I never saw a different, maybe it is hard to see in terms of quality.
I heard that in dark places the quality may became worse.
But sadly I don't have before and after photos in the exact same condition from a laboratory environment to compare.
